return {
  -- {
  --   "MeanderingProgrammer/render-markdown.nvim", -- Make Markdown buffers look beautiful
  --   ft = { "markdown", "codecompanion" },
  --   opts = {
  --     render_modes = true, -- Render in ALL modes
  --     sign = {
  --       enabled = false, -- Turn off in the status column
  --     },
  --   },
  --   dependencies = {
  --     {
  --       "nvim-treesitter/nvim-treesitter",
  --       opts = function(_, opts)
  --         if opts.ensure_installed ~= "all" then
  --           opts.ensure_installed =
  --             require("astrocore").list_insert_unique(opts.ensure_installed, { "markdown", "markdown_inline" })
  --         end
  --       end,
  --     },
  --   },
  -- },
}
